version: "2"

services:
  
  snapserver:
    image: daredoes/snapcast
    build: .
    volumes:
      - spotify-share:/data/spotify
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    command: snapserver -s pipe:///data/spotify/fifo?name=Spotify&sampleformat=44100:16:2
    
  spotify:
    image: daredoes/librespot
    volumes:
      - spotify-share:/data
    environment:
      SPOTIFY_NAME: Snapserver
      SPOTIFY_USER:     # set here or in .env file
      SPOTIFY_PASSWORD: # set here or in .env file

volumes:
  spotify-share:
